### ISSUE TITLE
upload the code?

### ISSUE THREAD

**Issue by Sukaiqi** [maiminh1996/SLS-Fusion#1]
Hello, I am very interested in your work. When will you upload the code?

**Comment by maiminh1996** [comment]
Thanks @Sukaiqi  for your attention. Now we are working with the extension of this work. Code and dataset will be published asap (within 1 month i think).

**Comment by Sukaiqi** [comment]
Thanks for your reply. I will continue to pay attention to your research.

**Comment by Sukaiqi** [comment]
Have you encountered any difficulties? I haven't seen your code upload so far.
